### ISSUE TITLE
New "enum" operand needed for some RiscV instructions

### ISSUE THREAD

**Issue by TheArni** [IBM/microprobe#17]
For some architectures such as RiscV some instructions (e.g. floating point instructions) have what could be described as an enum constant field, which the compiler then translates into the appropiate bitwise value to be encoded inside the instruction itself. Here is an example for RiscV, which involves multiple rounding modes for floating point operations: [Floating-point rounding modes](https://github.com/riscv/riscv-asm-manual/blob/master/riscv-asm.md#floating-point-rounding-modes).

At the moment instructions which use this field are implemented using a hard-coded value which might not always be the one used in the binary, resulting in a crash. There is a similar operand available, but it only works with integers. Maybe it could be adapted, although I'm not sure if it would work because enums have a key-value relation.

I propose the following interface for an ideal implementation, as an example I used the RiscV floating point instruction format with rounding mode field.

For the instruction format it should look as follows:
```yaml
- Name: "r-m+rf2"
  Fields:
  - funct5
  - funct2
  - rs2c
  - frs1
  - rm
  - rd
  - opcode
  Assembly: OPC rd, frs1, rm
```
And, for the `rm` field:
```yaml
- Name: "rm"
  Size: 3
  Description: "rm"
  Show: False
  IO: "?"
  Operand: "rm"
```

Finally, for the operand:
```yaml
- Name: rm
  Description: 3-bit immediate
  Enum:
  - [0, 'rne']
  - [1, 'rtz']
  - [2, 'rdn']
  - [3, 'rup']
  - [4, 'rmm']
  - [7, 'dyn']
```

As can be probably guessed, the first field in the array is the number the enum can be translated to, and the string is the enum's name to be used in the assembly language. Note the gap between the last two enums! The implementation should also take that into account.
